name: Maven CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn compile

    - name: Test with Maven
      run: mvn test

    - name: Package with Maven
      run: mvn package

    - name: Create artifact directory
      run: mkdir -p artifact && cp target/*.jar artifact

    - name: Upload Maven package artifact
      uses: actions/upload-artifact@v2
      with:
        name: Maven Package
        path: artifact
